#!/usr/bin/env node
// Draws the landing's terrain map once and writes the results into the app:
//   src/assets/terrain/*.webp                       ground (light, dark), clouds, cloud shadows
//   src/app/pages/landing/runtime/terrain-labels.js  label positions, kept as live text
// Needs Google Chrome and cwebp locally; the site build never runs this.
//   node scripts/terrain/bake.mjs
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '../..');
const CHROME = process.env.CHROME || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const ASSETS = join(REPO, 'src/assets/terrain');
const LABELS = join(REPO, 'src/app/pages/landing/runtime/terrain-labels.js');

const terrain = readFileSync(join(REPO, 'src/app/pages/landing/runtime/terrain.js'), 'utf8')
  .replace(/^\/\/ .*\n/, '')
  .replace(/^import .*\n/gm, '')
  .replace(/^export /gm, '');
const helpers = `const r1 = v => Math.round(v * 10) / 10;
const clamp = (v, a, b) => (v < a ? a : v > b ? b : v);
const mulberry = seed => () => { seed = (seed + 0x6D2B79F5) | 0; let t = Math.imul(seed ^ (seed >>> 15), 1 | seed); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };`;
const page = `<!doctype html><meta charset="utf-8"><body><script>\n${helpers}\n${terrain}\n${readFileSync(join(HERE, 'generate.js'), 'utf8')}\n</script></body>`;

const tmp = mkdtempSync(join(tmpdir(), 'terrain-bake-'));
try {
  writeFileSync(join(tmp, 'bake.html'), page);
  const dom = execFileSync(CHROME, ['--headless=new', '--disable-gpu', '--no-first-run', '--virtual-time-budget=60000', '--dump-dom', `file://${join(tmp, 'bake.html')}`], { maxBuffer: 256 * 1024 * 1024, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] });
  const error = dom.match(/data-error="([^"]*)"/);
  if (error) throw new Error(`bake failed in the browser: ${error[1]}`);
  if (!dom.includes('data-done="1"')) throw new Error('bake did not finish in the browser');
  const out = Object.fromEntries([...dom.matchAll(/<pre data-name="([^"]+)">([^<]*)<\/pre>/g)].map(m => [m[1], m[2]]));

  for (const [name, quality] of [['ground-light', 70], ['ground-dark', 70], ['clouds', 80], ['cloud-shadow', 80]]) {
    const png = join(tmp, `${name}.png`);
    writeFileSync(png, Buffer.from(out[`${name}.png`].replace(/^data:image\/png;base64,/, ''), 'base64'));
    execFileSync('cwebp', ['-quiet', '-q', String(quality), '-alpha_q', '90', '-m', '6', '-sharp_yuv', png, '-o', join(ASSETS, `${name}.webp`)]);
    console.log(`Wrote src/assets/terrain/${name}.webp`);
  }
  const labels = out['labels.json'].replace(/&quot;/g, '"').replace(/&amp;/g, '&');
  writeFileSync(LABELS, `// Generated by scripts/terrain/bake.mjs: where the terrain's labels sit on one ground tile.\nexport const TERRAIN_LABELS = ${labels};\n`);
  console.log('Wrote src/app/pages/landing/runtime/terrain-labels.js');
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
